apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv
  labels:
    type: local
spec:
  storageClassName: api
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/api"

