apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-init-pv
  labels:
    type: local
spec:
  storageClassName: mongo-init
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mongo-init/"
